# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 269)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 731, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 110, 731, 101))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 751, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuOT = QtWidgets.QMenu(self.menubar)
        self.menuOT.setObjectName("menuOT")
        self.menuNT = QtWidgets.QMenu(self.menubar)
        self.menuNT.setObjectName("menuNT")
        self.menuChap = QtWidgets.QMenu(self.menubar)
        self.menuChap.setObjectName("menuChap")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_from_BART_binary = QtWidgets.QAction(MainWindow)
        self.actionImport_from_BART_binary.setObjectName("actionImport_from_BART_binary")
        self.actionExport_as_BART_binary = QtWidgets.QAction(MainWindow)
        self.actionExport_as_BART_binary.setObjectName("actionExport_as_BART_binary")
        self.actionExport_for_Scripture_App_Builder = QtWidgets.QAction(MainWindow)
        self.actionExport_for_Scripture_App_Builder.setObjectName("actionExport_for_Scripture_App_Builder")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionX = QtWidgets.QAction(MainWindow)
        self.actionX.setObjectName("actionX")
        self.actionNew_project = QtWidgets.QAction(MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionEdit_project = QtWidgets.QAction(MainWindow)
        self.actionEdit_project.setObjectName("actionEdit_project")
        self.actionDelete_project = QtWidgets.QAction(MainWindow)
        self.actionDelete_project.setObjectName("actionDelete_project")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionImport_from_BART_binary)
        self.menuFile.addAction(self.actionExport_as_BART_binary)
        self.menuFile.addAction(self.actionExport_for_Scripture_App_Builder)
        self.menuFile.addAction(self.actionExit)
        self.menuProject.addAction(self.actionX)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionNew_project)
        self.menuProject.addAction(self.actionEdit_project)
        self.menuProject.addAction(self.actionDelete_project)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuOT.menuAction())
        self.menubar.addAction(self.menuNT.menuAction())
        self.menubar.addAction(self.menuChap.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuOT.setTitle(_translate("MainWindow", "OT"))
        self.menuNT.setTitle(_translate("MainWindow", "NT"))
        self.menuChap.setTitle(_translate("MainWindow", "Chap"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionImport_from_BART_binary.setText(_translate("MainWindow", "Import from BART binary"))
        self.actionExport_as_BART_binary.setText(_translate("MainWindow", "Export as BART binary"))
        self.actionExport_for_Scripture_App_Builder.setText(_translate("MainWindow", "Export for Scripture App Builder"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionX.setText(_translate("MainWindow", "X"))
        self.actionNew_project.setText(_translate("MainWindow", "New project"))
        self.actionEdit_project.setText(_translate("MainWindow", "Edit project"))
        self.actionDelete_project.setText(_translate("MainWindow", "Delete project"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

